/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-09 02:28:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bbs.BbsDAO;
import bbs.Bbs;
import java.io.PrintWriter;
import java.util.ArrayList;

public final class USer2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta\r\n");
      out.write("        http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <!-- 뷰포트 -->\r\n");
      out.write("        <meta\r\n");
      out.write("        name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\r\n");
      out.write("        <!-- 스타일시트 참조  -->\r\n");
      out.write("       \r\n");
      out.write("       <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("        <title>Main</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        body { padding-top: 30px; }\r\n");
      out.write("      \t.navbar-fixed-top{\r\n");
      out.write("      \t\tbackground-color: white;\r\n");
      out.write("      \t}\r\n");
      out.write("        .page-header{\r\n");
      out.write("            font-family: 'Playfair Display', serif;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }  \r\n");
      out.write("        h1{\r\n");
      out.write("        \tfont-family: 'ImcreSoojin';\r\n");
      out.write("        }\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'ImcreSoojin';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.3/ImcreSoojin.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    ");

	String userID=null;
	if(session.getAttribute("userID")!=null){
		userID=(String)session.getAttribute("userID");
	}
    
      out.write("\r\n");
      out.write("    <nav class=\"navbar-fixed-top navbar-default\">\r\n");
      out.write("    \t<div class=\"container-fluid\">\r\n");
      out.write("    \t\t<div class=\"navbar-header\">\r\n");
      out.write("            \t<a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                \t<span class=\"glyphicon glyphicon-align-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("                </a>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("            \t<a href=\"Index.jsp\"><img alt=\"Brand\" width=120px; height=40px;\" style=\"margin-top: 8px;\" src=\"./img/logo.JPG\"></a>       \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("          \t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("      \t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("              \t\t<li><a href=\"Write.jsp\">WRITE</a></li>\r\n");
      out.write("              \t\t<li><a href=\"#\">##</a></li>\r\n");
      out.write("              \t\t<li><a href=\"#\">##</a></li>\r\n");
      out.write("              \t\t<li><a href=\"User.jsp\">USER</a></li>\r\n");
      out.write("            \t</ul>\r\n");
      out.write("          <form class=\"navbar-form navbar-right\" role=\"search\" action=\"Search.jsp\">\r\n");
      out.write("          \t<div class=\"form-group\">\r\n");
      out.write("          \t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\" name=\"userName\">\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t<button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("      \t  </form>\r\n");
      out.write("            \r\n");
      out.write("            ");

            	if(userID==null){
            
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li><a href=\"Login.jsp\">LOGIN</a></li>\r\n");
      out.write("              <li><a href=\"Join.jsp\">JOIN</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");

            	}else{
            
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li><a href=\"LogoutAction.jsp\">LOGOUT</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");

            	}
            
      out.write("\r\n");
      out.write("          </div><!-- /.navbar-collapse -->\r\n");
      out.write("        </div><!-- /.container-fluid -->\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- \t\t\t<div class=\"col-md-3\">\r\n");
      out.write("        \t\t\t<div class=\"card\">\r\n");
      out.write("  \t\t\t\t\t\t\t<img src=\"./img/grass.png\" id=\"img_click\" style=\"cursor:pointer;\" class=\"card-img-top\" alt=\"Profile\">  \t\t\t\t\t\t\t \t\t\t\t\t \t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t<div class=\"card-body\">  \t\t\t\t\t\t \t\t\t\t\t  \t\t\t\t\t \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t<h5 class=\"card-title\">aaaaaaaaaaa</h5>   \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"media my-4\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t<span class=\"far fa-building\"></span>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t\t<p class=\"mt-0 mb-1\">&nbsp;&nbsp;aaaaaaa</p>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</li>  \t\t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<li class=\"media my-4\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t<span class=\"far fa-envelope\"></span>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t<p class=\"mt-0 mb-1\">&nbsp;&nbsp;aaaaaaa</p>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</li>  \t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Change.jsp\" class=\"btn btn-success\">수정하기</a>\r\n");
      out.write("  \t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div> \r\n");
      out.write("  \t\t\t\t\t</div> -->\r\n");
      out.write("  \t\t\t\t\t<!-- <div class=\"row\">\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"col-sm-6 col-md-4\">\r\n");
      out.write("   \t\t\t\t\t\t <div class=\"thumbnail\">\r\n");
      out.write("      \t\t\t\t\t\t<img src=\"...\" alt=\"...\">\r\n");
      out.write("     \t\t\t\t\t\t\t <div class=\"caption\">\r\n");
      out.write("       \t\t\t\t\t\t\t\t <h3>Thumbnail label</h3>\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<p>...</p>\r\n");
      out.write("       \t\t\t\t\t\t\t\t\t\t <p><a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a href=\"#\" class=\"btn btn-default\" role=\"button\">Button</a></p>\r\n");
      out.write("      \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<!--  \t<div style=\"margin-left:auto;margin-right:auto;\">\r\n");
      out.write("        <div class=\"col-lg-6\" style=\"padding-top: 50px;\"> \r\n");
      out.write("              <div class=\"form\">           \r\n");
      out.write("                <img src=\"./img/grass.png\" width=250px; height=auto; id=\"img_click\" style=\"cursor:pointer;\" alt=\"Profile\"> \r\n");
      out.write("                 <h5 class=\"card-title\">aaaaaaaaaaa</h5>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("          \r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-5\" style=\"padding-top: 210px;padding-bottom: 100px\"> \r\n");
      out.write("          <img width=\"100%\";height=\"auto\"; src=\"./img/로그인.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  \t\t\t -->\r\n");
      out.write("  \t\t\t <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("  \t\t\t \t<div class=\"card\" style=\"width:300px;margin-top:40px;\">\r\n");
      out.write("  \t\t\t \t<image class=\"card-img-top\" src=\"./img/grass.png\" style=\"width:100%\">\r\n");
      out.write("   \t\t\t \t\t<div class=\"card-body\">\r\n");
      out.write("  \t\t\t \t\t\t<h4 class=\"card-title\">형연이</h4>\r\n");
      out.write("  \t\t\t \t\t\t<p class=\"card-text\">adafadfadfa</p>\r\n");
      out.write("  \t\t\t \t\t\t<a href=\"#\" class=\"btn btn-primary\">dfadfa</a>\r\n");
      out.write("  \t\t\t \t\t</div>\r\n");
      out.write("  \t\t\t \t\t\r\n");
      out.write("  \t\t\t </div>\r\n");
      out.write("  \t\t\t \r\n");
      out.write("  \t\t\t \t\t\t\t<!-- Modal -->\r\n");
      out.write("  \t\t\t\t\t\t\t<div class=\"modal\" id=\"myModal\" tabindex=\"-1\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("    \t\t\t\t\t    \t\t\t<div class=\"modal-header\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          \t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t</div>      \t\t\t\t\t      \t\t\t\t\r\n");
      out.write("      \t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"tooltip-test\" title=\"Tooltip\">프로필 사진 수정</a><br>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"tooltip-test\" title=\"Tooltip\">기본 이미지로 변경</a>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- The Modal -->\r\n");
      out.write("  \t\t\t\t\t\t\t  <script type=\"text/javascript\">\r\n");
      out.write("  \t\t\t\t\t\t\t\tvar modal = document.getElementById('myModal');\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t// Get the button that opens the modal\r\n");
      out.write("    \t\t\t\t\t\t\tvar btn = document.getElementById(\"img_click\");\r\n");
      out.write("\r\n");
      out.write("   \t\t\t\t\t\t\t\t// Get the <span> element that closes the modal\r\n");
      out.write("    \t\t\t\t\t\t\tvar span = document.getElementsByClassName(\"close\")[0];                                          \r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t// When the user clicks on the button, open the modal \r\n");
      out.write("    \t\t\t\t\t\t\tbtn.onclick = function() {\r\n");
      out.write("    \t\t\t\t\t\t\t    modal.style.display = \"block\";\r\n");
      out.write("    \t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t// When the user clicks on <span> (x), close the modal\r\n");
      out.write("    \t\t\t\t\t\t\tspan.onclick = function() {\r\n");
      out.write("        \t\t\t\t\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("    \t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t\t// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("    \t\t\t\t\t\t\twindow.onclick = function(event) {\r\n");
      out.write("        \t\t\t\t\t\t\tif (event.target == modal) {\r\n");
      out.write("            \t\t\t\t\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("        \t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t</script>\r\n");
      out.write("    \t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
